{{- if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "duna.fullname" . }}-backup
  labels:
    {{- include "duna.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  {{- if .Values.backup.concurrencyPolicy }}
  concurrencyPolicy: {{ .Values.backup.concurrencyPolicy | quote }}
  {{- end }}
  {{- if .Values.backup.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.backup.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.backup.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.backup.failedJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "duna.selectorLabels" . | nindent 12 }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- if .Values.imageCredentials.pullSecret }}
          imagePullSecrets:
            - name: {{ .Values.imageCredentials.pullSecret }}
          {{- else if eq .Values.imageCredentials.enabled true }}
          imagePullSecrets:
            - name: {{ include "duna.fullname" . }}-pull-secret
          {{- end }}
          serviceAccountName: {{ include "duna.serviceAccountName" . }}
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: >-
                {{ .Values.image.repository }}
                {{- if .Values.image.digest }}@{{ .Values.image.digest }}
                {{- else }}:{{ .Values.image.tag | default .Chart.AppVersion }}{{- end }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /bin/bash
                - /app/start-backup.sh
              volumeMounts:
                - name: {{ include "duna.fullname" . }}-config-volume
                  mountPath: "/app/config"
                  readOnly: true
                - name: {{ include "duna.fullname" . }}-tls-cert
                  mountPath: "/etc/nginx/tls"
                  readOnly: true
          volumes:
            - name: {{ include "duna.fullname" . }}-config-volume
              secret:
                secretName: {{ .Values.duna.configSecret }}
            - name: {{ include "duna.fullname" . }}-tls-cert
              secret:
                secretName: {{ (index .Values.ingress.tls 0).secretName }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
