apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "duna.fullname" . }}
  labels:
    {{- include "duna.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "duna.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "duna.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imageCredentials.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.pullSecret }}
      {{- else if eq .Values.imageCredentials.enabled true }}
      imagePullSecrets:
        - name: {{ include "duna.fullname" . }}-pull-secret
      {{- end }}
      serviceAccountName: {{ include "duna.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: >-
            {{ .Values.image.repository }}
            {{- if .Values.image.digest }}@{{ .Values.image.digest }}
            {{- else }}:{{ .Values.image.tag | default .Chart.AppVersion }}{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:        
            - name: CONFIG_FILE
              value: "/app/config/config.yaml"

          volumeMounts:
            - name: {{ include "duna.fullname" . }}-config-dir
              mountPath: "/app/config"
            - name: {{ include "duna.fullname" . }}-config-volume
              mountPath: "/app/config/config.yaml"
              subPath: "config.yaml"
              readOnly: true
            - name: {{ include "duna.fullname" . }}-tls-cert
              mountPath: "/etc/nginx/tls"
              readOnly: true
            {{- if .Values.authlanceLicense.secretName }}
            - name: {{ include "duna.fullname" . }}-authlance-license
              mountPath: "/app/config/authlance.lic"
              subPath: "authlance.lic"
              readOnly: true
            {{- end }}

          # 
          # Set container configuration
          #
          ports:
            - name: http
              containerPort: 1080
              protocol: TCP
            - name: http-mail
              containerPort: 8001
              protocol: TCP
          
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.duna.basePath }}/identity/api/v1/health
              port: http
          
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.duna.basePath }}/identity/api/v1/health
              port: http

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "duna.fullname" . }}-config-dir
          emptyDir: {}
        - name:  {{ include "duna.fullname" . }}-config-volume
          secret:
            secretName: {{ .Values.duna.configSecret }}
        - name: {{ include "duna.fullname" . }}-tls-cert
          secret:
            secretName: {{ (index .Values.ingress.tls 0).secretName }}
        {{- if .Values.authlanceLicense.secretName }}
        - name: {{ include "duna.fullname" . }}-authlance-license
          secret:
            secretName: {{ .Values.authlanceLicense.secretName }}
            items:
              - key: authlance.lic
                path: authlance.lic
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
