apiVersion: v1
kind: Service
metadata:
  name: {{ include "duna.fullname" . }}
  labels:
    {{- include "duna.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http  
  selector:
    {{- include "duna.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "duna.fullname" . }}-auth-mail
  labels:
    {{- include "duna.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8001
      targetPort: http-mail
      protocol: TCP
      name: http-mail  
  selector:
    {{- include "duna.selectorLabels" . | nindent 4 }}
