apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "duna.fullname" . }}
  labels:
    {{- include "duna.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "duna.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "duna.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imageCredentials.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.pullSecret }}
      {{- else if eq .Values.imageCredentials.enabled true }}
      imagePullSecrets:
        - name: {{ include "duna.fullname" . }}-pull-secret
      {{- end }}
      serviceAccountName: {{ include "duna.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: >-
            {{ .Values.image.repository }}
            {{- if .Values.image.digest }}@{{ .Values.image.digest }}
            {{- else }}:{{ .Values.image.tag | default .Chart.AppVersion }}{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: CONFIG_FILE
              value: "/app/config/config.yaml"

          volumeMounts:
            - name: {{ include "duna.fullname" . }}-config-volume
              mountPath: "/app/config"
              readOnly: true
            - name: {{ include "duna.fullname" . }}-tls-cert
              mountPath: "/etc/nginx/tls"
              readOnly: true

          ports:
            - name: http
              containerPort: 1080
              protocol: TCP
          
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: /healthz
              port: http
          
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: /healthz
              port: http

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name:  {{ include "duna.fullname" . }}-config-volume
          projected:
            sources:
              - secret:
                  name: {{ .Values.duna.configSecret }}
              {{- if .Values.authlanceLicense.secretName }}
              - secret:
                  name: {{ .Values.authlanceLicense.secretName }}
                  items:
                    - key: authlance.lic
                      path: authlance.lic
              {{- end }}
        - name: {{ include "duna.fullname" . }}-tls-cert
          secret:
            secretName: {{ (index .Values.ingress.tls 0).secretName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
